<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2Of1NLM\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2Of1NLM/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container2Of1NLM.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container2Of1NLM\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container2Of1NLM\appAppKernelProdContainer([
    'container.build_hash' => '2Of1NLM',
    'container.build_id' => '0e647d16',
    'container.build_time' => 1721038060,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2Of1NLM');
